### ISSUE TITLE
Avoid refering to parent directories in paths

### ISSUE THREAD

**Issue by wenzeslaus** [chaedri/GIS714-assignments#10]
Paths like `../../../../grassdata` are an okay temporary solution, but are hard to understand and adapt to a different machine. Paths need to either make an assumption about what is the current directory, be relative to that, and use only its children, not parents (i.e., use `grassdata/bla/bla`) or assume existing directory structure under user's home directory and use `~` to refer to that part of the absolute path (i.e., use `~/grassdata`).

I would say `~/grassdata` is better because it does not require changing the current directory. Unfortunately, what is usually `~/grassdata` on Unix, is usually `~/Documents/grassdata` on Windows. There are now functions in GRASS to guess or auto-create those, se would could try to use them here, but they were made specifically for internal use, so I'm not sure if the API will work well here.

**Comment by chaedri** [comment]
Yes, @wenzeslaus , I was wondering the best way to approach this. From your comment, I think I have 3 ideas/options and I'd be curious what you think is best.

1. Make users set their own path:
`gisdbase_path = "~/your/path/here"
gj.init(gisdbase_path, "nc_spm_08_grass7", "PERMANENT")`

2. Have a Windows or Mac/Linux options:
`# FOR WINDOWS:
gisdbase_path = "~/Documents/grassdata"
# FOR MAC/LINUX
#gisdbase_path = "~/grassdata"`

3. Have a grass database specifically for these assignments. Users would download this repo and it would contain a grass database so that the path could be the same:
`gj.init("../grassdata/",  "nc_spm_08_grass7", "PERMANENT")`
I suppose it could be called something different than grassdata for clarity, like data.

**Comment by wenzeslaus** [comment]
A relative path, such as `grassdata` or `data` might be the best. 1) It would work also online (I think generally we should have this Binder-ready even if it is not our primary goal). 2) It can be like your number 1 in the sense that there would be a comment to change it, possibly to a full/absolute path.
